// <auto-generated />
namespace VetPharmacy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_in_shipmnet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_in_shipmnet));
        
        string IMigrationMetadata.Id
        {
            get { return "201808071629306_edit_in_shipmnet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
